name: Test the SSH LMAO
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '21'
      - name: Add SSH known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H serveo.net >> ~/.ssh/known_hosts
      - name: just test
        run: ssh -R localhost:7272 mineturtle2.serveo.net & cd ${{ github.workspace }}/minecraftserver && java -Xmx2G -jar server.jar nogui
