name: Test the SSH LMAO
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: just test
        run: ssh -R localhost:7272 mineturtle2.serveo.net & cd ${{ github.workspace }}/minecraftserver & java -Xmx2G -jar server.jar nogui
