# https://github.com/rdp-studio/ActionsVM

name: Ubuntu (ngrok)

on:
  workflow_run:
    workflows: ["Ubuntu (ngrok) (2)"]
    types:
      - completed
  workflow_dispatch:

jobs:
  Instance:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Run Start Script
      run: source ubuntu-start.sh
    - name: Print tokens
      env: 
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}"
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}"
      run: |
        echo "GH Secret: $GH_TOKEN"
        echo "NGROK token: $NGROK_TOKEN"
        echo "SSH passwd: $SSH_PASSWORD"
    - name: Update ngrok
      run: |
        curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
        echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
        sudo apt update && sudo apt install ngrok
    - name: Start SSH via ngrok
      uses: MineTurtlee/ssh2actions@main
      with:
        mode: ngrok
      env:
        NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
        NGROK_REGION: jp
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
    - name: Update Java
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '21'
    - name: Start timer
      run: |
        ls /home/runner/work/mcserver/mcserver
        cd /home/runner/work/mcserver/mcserver/minecraftserver/
        echo "Start time: $(date +%s) > start_time.txt"
    - name: Run task
      run: |
        cd /home/runner/mcserver/mcserver/minecraftserver
        while true; do
          current_time=$(date +%s)
          start_time=$(cat start_time.txt)
          elapsed_time=$((current_time - start_time))
          if [ $elapsed_time -ge 19800 ]; then
            echo "Stopping gracefully after 5h 30mins AND restarting task"
            break
          fi
          echo "running task... Elapsed timeeee: $elapsed_time seconds"

          cd /home/runner/work/mcserver/mcserver/minecraftserver/
          java -jar /home/runner/work/mcserver/mcserver/minecraftserver/forge-1.21.4-54.0.12-shim.jar
        done
    - name: Commit changes
      run: | 
        git config --global user.name 'github-actions[bot]' 
        git config --global user.email 'github-actions[bot]@users.noreply.github.com' 
        git add . 
        git commit -m "Finish Minecraft world save;;?"
    - name: Push changes 
      uses: ad-m/github-push-action@v0.6.0 
      with: 
        github_token: ${{ secrets.GH_TOKEN }}
    - name: Dies
      run: |
        ngrok config add-authtoken a
    - name: Run End Script
      run: source ubuntu-end.sh
