# https://github.com/rdp-studio/ActionsVM

name: Ubuntu (ngrok)

on:
  workflow_dispatch:

jobs:
  Instance:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Run Start Script
      run: source ubuntu-start.sh
    - name: Print tokens
      run: |
        echo "::add-mask::${{ secrets.GH_TOKEN }}"
        echo "GH Secret: ${{ secrets.GH_TOKEN }}"
        echo "::add-mask::${{ secrets.NGROK_TOKEN }}"
        echo "NGROK token: ${{ secrets.NGROK_TOKEN }}"
        echo "::add-mask::${{ secrets.SSH_PASSWORD }}"
        echo "SSH passwd: ${{ secrets.SSH_PASSWORD }}"

    - name: Start SSH via ngrok
      uses: rdp-studio/ssh2actions@main
      with:
        mode: ngrok
      env:
        NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
        NGROK_REGION: jp
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
    - name: Commit changes
      run: | 
        git config --global user.name 'github-actions[bot]' 
        git config --global user.email 'github-actions[bot]@users.noreply.github.com' 
        git add . 
        git commit -m "Automated commit message"
    - name: Push changes 
      uses: ad-m/github-push-action@v0.6.0 
      with: 
        github_token: ${{ secrets.GH_TOKEN }}

    - name: Run End Script
      run: source ubuntu-end.sh
