# https://github.com/rdp-studio/ActionsVM

name: UbuntuMain

on:
  workflow_run:
    workflows: ["Ubuntu"]
    types:
      - completed
  workflow_dispatch:

jobs:
  Instance:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@main
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '21'
    - name: Run Start Script
      run: source ubuntu-start.sh
    - name: Print tokens
      env: 
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}"
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}"
      run: |
        echo "GH Secret: $GH_TOKEN"
        echo "NGROK token: $NGROK_TOKEN"
        echo "SSH passwd: $SSH_PASSWORD"
    - name: open frieawlsk
      run: sudo ufw allow 7272/tcp
    - name: Run script
      env:
        Bot_Token: ${{ secrets.BOT_TOKEN }}
        Channel_ID: ${{ secrets.CHANNEL_ID }}
        SL: ${{ secrets.SERVER_LINK }}
      run: |
        cd ${{ GITHUB.WORKSPACE }}/minecraftserver
        pip install discord
        python3 start.py
    - name: Commit changes
      run: | 
        git config --global user.name 'github-actions[bot]' 
        git config --global user.email 'github-actions[bot]@users.noreply.github.com' 
        git add . 
        git commit -m "Finish Minecraft world save;;?"
        git push
    - name: Dies
      run: |
        ngrok config add-authtoken a
    - name: Run End Script
      run: source ubuntu-end.sh
