# https://github.com/rdp-studio/ActionsVM

name: Ubuntu (ngrok)

on:
  workflow_dispatch:

jobs:
  Instance:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Run Start Script
      run: source ubuntu-start.sh
    - name: Print tokens
      env: 
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}"
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}"
      run: |
        echo "GH Secret: $GH_TOKEN"
        echo "NGROK token: $NGROK_TOKEN"
        echo "SSH passwd: $SSH_PASSWORD"
    - name: install ngrok but idk whar
      run: |
        curl -s https://| curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc > /dev/null
        echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
        sudo apt-get update && sudo apt-get install ngrok
    - name: Check ngrok version 
      id: check_version 
      run: | 
        INSTALLED_VERSION=$(ngrok version | grep -oP 'ngrok version \K[0-9.]+') 
        ONLINE_VERSION=$(curl -s https://ngrok.com/download | grep -oP 'ngrok version \K[0-9.]+') 
        echo "INSTALLED_VERSION=$INSTALLED_VERSION" >> $GITHUB_ENV 
        echo "ONLINE_VERSION=$ONLINE_VERSION" >> $GITHUB_ENV 
    - name: Update ngrok if version unmatches 
      if: env.INSTALLED_VERSION != env.ONLINE_VERSION 
      run: | 
        sudo apt-get install --only-upgrade ngrok 
        echo "ngrok updated to version $(ngrok version)"
    - name: Start SSH via ngrok
      uses: rdp-studio/ssh2actions@main
      with:
        mode: ngrok
      env:
        NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
        NGROK_REGION: jp
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
    - name: Commit changes
      run: | 
        git config --global user.name 'github-actions[bot]' 
        git config --global user.email 'github-actions[bot]@users.noreply.github.com' 
        git add . 
        git commit -m "Automated commit message"
    - name: Push changes 
      uses: ad-m/github-push-action@v0.6.0 
      with: 
        github_token: ${{ secrets.GH_TOKEN }}

    - name: Run End Script
      run: source ubuntu-end.sh
